//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stef.DatabaseQuery.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stef.DatabaseQuery.Business.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD
        ///EXTERNAL
        ///PROCEDURE
        ///ALL
        ///FETCH
        ///PUBLIC
        ///ALTER
        ///FILE
        ///RAISERROR
        ///AND
        ///FILLFACTOR
        ///READ
        ///ANY
        ///FOR
        ///READTEXT
        ///AS
        ///FOREIGN
        ///RECONFIGURE
        ///ASC
        ///FREETEXT
        ///REFERENCES
        ///AUTHORIZATION
        ///FREETEXTTABLE
        ///REPLICATION
        ///BACKUP
        ///FROM
        ///RESTORE
        ///BEGIN
        ///FULL
        ///RESTRICT
        ///BETWEEN
        ///FUNCTION
        ///RETURN
        ///BREAK
        ///GOTO
        ///REVERT
        ///BROWSE
        ///GRANT
        ///REVOKE
        ///BULK
        ///GROUP
        ///RIGHT
        ///BY
        ///HAVING
        ///ROLLBACK
        ///CASCADE
        ///HOLDLOCK
        ///ROWCOUNT
        ///CASE
        ///IDENTITY
        ///ROWGUIDCOL
        ///CHECK
        ///IDENTITY_INSERT
        ///RULE
        ///CHECKPOINT
        ///IDENTITYCOL
        ///SAVE
        ///CLOSE
        ///IF
        ///SCHEMA
        ///CLUSTER [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlReservedWords {
            get {
                return ResourceManager.GetString("SqlReservedWords", resourceCulture);
            }
        }
    }
}
